name: Docker Image CI

on: [push]

jobs:

  build:
    name: Docker CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dockerhub Login
      id: docker-login
      run: echo ""${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build image
      id: docker-build
      run: docker build . --file Dockerfile --tag colombia-mission-test:$(date +%s)
    - name: Push image
      id: docker-push
      run: docker push colombia-mission-test:$(date +%s)
      
